version: '3.8'

services:
  # Cấu hình cho SQL Server (UserService)
  userservice-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: userservice_sqlserver
    environment:
      SA_PASSWORD: "SuperStrong!P@ssw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    networks:
      - app_network
    restart: always

  # Cấu hình API UserService
  userservice-api:
    build:
      context: .
      dockerfile: src/Services/UserService/API/Dockerfile
    container_name: userservice_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Stagging"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "7000:80"
    depends_on:
      - userservice-db
    networks:
      - app_network
    restart: always

  # Cấu hình MongoDB (ProductService)
  productservice-db:
    image: mongo:latest
    container_name: productservice_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27018:27017"
    networks:
      - app_network
    restart: always

  # Cấu hình API ProductService
  productservice-api:
    build:
      context: .
      dockerfile: src/Services/ProductService/API/Dockerfile
    container_name: productservice_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Stagging"
      ASPNETCORE_URLS: "http://+:80"
      MONGO_CONNECTION_STRING: "mongodb://admin:password@productservice-db:27017/"
      MONGO_DATABASE: "ProductDb"
    ports:
      - "7001:80"
    depends_on:
      - productservice-db
    networks:
      - app_network
    restart: always

  # 🐰 Cấu hình RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "StrongPass123!"
    ports:
      - "5673:5672"  # Port RabbitMQ (5672 mặc định, đổi thành 5673)
      - "15673:15672" # Management UI (đổi từ 15672 thành 15673)
    networks:
      - app_network
    restart: always


networks:
  app_network:
    driver: bridge
