version: '3.8'

services:
  # Cấu hình cho cơ sở dữ liệu SQL Server
  userservice-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: userservice_sqlserver
    environment:
      SA_PASSWORD: "SuperStrong!P@ssw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    networks:
      - userservice_network
    restart: always

  # Cấu hình cho API của bạn
  userservice-api:
    build:
      context: .  # Dùng thư mục gốc làm context
      dockerfile: src/Services/UserService/API/Dockerfile  # Cập nhật lại đường dẫn
    container_name: userservice_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"  # Thêm dòng này để ép ASP.NET chạy trên cổng 80
    ports:
      - "9001:80"   # Expose cổng của API
    depends_on:
      - userservice-db  # Đảm bảo DB đã sẵn sàng trước khi API khởi động
    networks:
      - userservice_network
    restart: always


networks:
  userservice_network:
    driver: bridge